Springjpa 1 movie init sql
neosuniversity-team/neosuniversity-video-library pull request #1
Opened 2020-08-10 00:41 UTC by neossoftware

@hhugohm tu apoyo en la revisión

2020-08-10 01:08 UTC, hhugohm requested changes
Favor de revisar el cambio propuesto en tu script

2020-08-10 01:08 UTC, hhugohm commented on src/main/resources/sql/database.sql
> +CREATE DATABASE videodb CHARACTER SET utf8 COLLATE utf8_spanish_ci;
seria mejor cambiar
de : `CREATE DATABASE videodb CHARACTER SET utf8 COLLATE utf8_spanish_ci;`
a: `CREATE DATABASE videodb CHARACTER SET latin1 COLLATE latin1_spanish_ci ;`

estas de acuerdo?

2020-08-10 21:54 UTC, neossoftware commented on src/main/resources/sql/database.sql
> +CREATE DATABASE videodb CHARACTER SET utf8 COLLATE utf8_spanish_ci;
Arre me late

2020-08-10 21:56 UTC, neossoftware commented
@hhugohm Se atendieron los cambios solicitados.

2020-08-11 00:10 UTC, hhugohm approved these changes
Aprobada

Nota: Hola bro, solo q veo q la rama q tienes tu cambio no esta actulizada con todos los cambios, favor de antes de hacer merge, hagas un pull de forma local y veas todos los cambios q hay. Asi evitaras planchar algo mas.

2020-08-11 00:13 UTC, hhugohm commented
Hola bro, solo q veo q la rama q tienes tu cambio no esta actulizada con todos los cambios, favor de antes de hacer merge, hagas un pull de forma local y veas todos los cambios q hay. Asi evitaras planchar algo mas.

saludos

2020-08-11 01:02 UTC, neossoftware commented
@Gracias, ok lo reviso entonces mañana antes de hacer merge

2020-08-16 21:57 UTC, merged